### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by esbovee** [olly-styles/WorkBench#48]
In ReadMe under **EVALUATION** text should be changed from:

"Not that results are not provided for the all_tools variant of GPT3.5 and LLama2-70B as the prompt does not fit into the context window for these models."

to 

"Note that results are not provided for the all_tools variant of GPT3.5 and LLama2-70B as the prompt does not fit into the context window for these models."

**Comment by sammiller06** [comment]
Good spot, thanks @esbovee . Fixed that now, welcome to the repo :)
