### ISSUE TITLE
License for Code/Data?

### ISSUE THREAD

**Issue by jgung** [olly-styles/WorkBench#49]
Thanks for your great work and for releasing your code and data! @olly-styles 

Would it be possible to add a license for the code and data to your repo? Depending on the license, this will enable others to use it in other work and possibly modify/extend it. Thanks in advance for your reply!

**Comment by olly-styles** [comment]
We’re looking at this now and will have an updated licence soon. Apologies for the delay and thank you for your patience!

**Comment by olly-styles** [comment]
Just added an MIT licence. Thanks again for your patience.
