### ISSUE TITLE
Incomplete docs for `search_emails`

### ISSUE THREAD

**Issue by alexcoca** [olly-styles/WorkBench#50]
The documentation for the `search_emails` tool does not specify the limit (unlike, for example `search_events`)? Is this a deliberate choice or omission?

**Comment by olly-styles** [comment]
Excellent spot @alexcoca! Thank you. 

This is a mistake on our part. This omission will have a small impact on results.

**Comment by alexcoca** [comment]
Thanks @olly-styles , and congrats on the work to you and your collaborators, it's great.
